/**
 * This file describes different game definitions to keep content consistent
 * between client and server. Ex: How much damage does a cannonball do?
 *
 * Sprites are not included here, but in the client. Sprites are not needed on a server.
 */

import {
  EntityType,
  MapEntityDef,
  MapObjectDef,
  PlayerDef,
  TerrainDef,
} from "./Objects";

export const TILE_SIZE: number = 32;
export const TILE_SIZE_WITH_BUFFER: number = 46;
export const KILL_REWARD: number = 100;
export const STARTING_CANNON_BALLS: number = 100;
export const STARTING_MONEY: number = 10;
export const WOOD_HEAL: number = 5;
export const SPRITE_SHEET_WIDTH: number = 25;
export const SPRITE_SHEET_HEIGHT: number = 25;
export const SPRITE_SHEET_TILE_SIZE: number = 64;
export const TREASURE_CHANCE: number = 300;
export const TREASURE_REWARD_MAX: number = 20;
export const RESPAWN_DELAY = 5000;
export const HEALTH = 100;

export const UPGRADE_MEDIC_HEAL_PER_TICK = 0.005; // about 1 a second
export const UPGRADE_MAX_HEALTH = 150;
export const UPGRADE_WATER_RESISTANCE = 0.9;

/**
 * The id of a terrain is not the type, but the id generated by Tiled.
 * Since this list is exaustive and never used anywhere, we include the
 * actual value instead of an enum. This is refered to as the terrainId.
 *
 * If there is no value, DefaultTerrainDef is used
 */
export let TerrainDefs: { [id: number]: TerrainDef } = {};

TerrainDefs[100] = {
  damage: 10,
  id: 0,
  collisionMap:
    "000000010000003f000003ff00001fff0000ffff0007ffff001fffff007fffff01ffffff03ffffff07ffffff0fffffff1fffffff1fffffff3fffffff3fffffff7fffffff7fffffff7fffffff7fffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:32,32",
};

TerrainDefs[102] = {
  damage: 10,
  id: 102,
  collisionMap:
    "ffc00000ffff0000ffffc000fffff000fffff800fffffe00fffffe00ffffff00ffffff00ffffff80ffffff80ffffffc0ffffffc0ffffffe0ffffffe0ffffffe0fffffff0fffffff0fffffff0fffffff8fffffff8fffffff8fffffffcfffffffcfffffffcfffffffcfffffffefffffffefffffffefffffffefffffffeffffffff:32,32",
};

TerrainDefs[103] = {
  damage: 10,
  id: 103,
  collisionMap:
    "000000010000003f000003ff00001fff0000ffff0007ffff001fffff007fffff01ffffff03ffffff07ffffff0fffffff1fffffff1fffffff3fffffff3fffffff7fffffff7fffffff7fffffff7fffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:32,32",
};

TerrainDefs[106] = {
  damage: 10,
  id: 106,
  collisionMap:
    "ffc00000ffff0000ffffc000fffff000fffff800fffffe00fffffe00ffffff00ffffff00ffffff80ffffff80ffffffc0ffffffc0ffffffe0ffffffe0ffffffe0fffffff0fffffff0fffffff0fffffff8fffffff8fffffff8fffffffcfffffffcfffffffcfffffffcfffffffefffffffefffffffefffffffefffffffeffffffff:32,32",
};

TerrainDefs[150] = {
  damage: 10,
  id: 150,
  collisionMap:
    "ffffffff7fffffff7fffffff7fffffff7fffffff7fffffff3fffffff3fffffff3fffffff3fffffff1fffffff1fffffff1fffffff0fffffff0fffffff0fffffff07ffffff07ffffff07ffffff03ffffff03ffffff01ffffff01ffffff00ffffff00ffffff007fffff003fffff001fffff000fffff0003ffff0000ffff000007ff:32,32",
};

TerrainDefs[152] = {
  damage: 10,
  id: 152,
  collisionMap:
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffcfffffffcfffffff8fffffff8fffffff0fffffff0ffffffe0ffffff80fffffe00fffff800ffffe000ffff0000fff80000ffc00000fc000000c0000000:32,32",
};

TerrainDefs[178] = {
  damage: 10,
  id: 178,
  collisionMap:
    "ffffffff7fffffff7fffffff7fffffff7fffffff7fffffff3fffffff3fffffff3fffffff3fffffff1fffffff1fffffff1fffffff0fffffff0fffffff0fffffff07ffffff07ffffff07ffffff03ffffff03ffffff01ffffff01ffffff00ffffff00ffffff007fffff003fffff001fffff000fffff0003ffff0000ffff000007ff:32,32",
};

TerrainDefs[181] = {
  damage: 10,
  id: 181,
  collisionMap:
    "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffffefffffffefffffffefffffffefffffffcfffffffcfffffff8fffffff8fffffff0fffffff0ffffffe0ffffff80fffffe00fffff800ffffe000ffff0000fff80000ffc00000fc000000c0000000:32,32",
};

TerrainDefs[200] = {
  damage: 10,
  id: 200,
  collisionMap:
    "00000000000000000000000000000000000000000000000000000000000fe000001ff000001ff800003ffc00003ffe00007ffe00007fff0000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff80000fff800000ff8000000000000000000000000000000000000000000000000000000000:32,32",
};

TerrainDefs[201] = {
  damage: 10,
  id: 201,
  collisionMap:
    "000000000000000000000000000000000038000000fe000003ff80000fffe0003fffffc03fffffe03ffffff01ffffff00ffffff80ffffffc07fffffc03fffffc07fffffc07fffffc07fffffc07fffff80ffffff80ffffff807fffff801fffff0007fffe0001fff800001ff0000003e0000000000000000000000000000000000:32,32",
};

TerrainDefs[202] = {
  damage: 10,
  id: 202,
  collisionMap:
    "0000000000000000000000000000000000000000000000000000f0000003f800000ff800003ffc0000fffe0001ffff0003ffff8003ffff8003ffffc003ffffc003ffffc003ffffc003ffff8003ffff0003ffff0003fffe0003fffc0001fffc00001ff8000003f000000000000000000000000000000000000000000000000000:32,32",
};

TerrainDefs[203] = {
  damage: 10,
  id: 203,
  collisionMap:
    "00000000000000000000000000000000000000000000000000000000000fe000001ff000001ff800003ffc00003ffe00007ffe00007fff0000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff8000ffff80000fff800000ff8000000000000000000000000000000000000000000000000000000000:32,32",
};

TerrainDefs[204] = {
  damage: 10,
  id: 204,
  collisionMap:
    "000000000000000000000000000000000038000000fe000003ff80000fffe0003fffffc03fffffe03ffffff01ffffff00ffffff80ffffffc07fffffc03fffffc07fffffc07fffffc07fffffc07fffff80ffffff80ffffff807fffff801fffff0007fffe0001fff800001ff0000003e0000000000000000000000000000000000:32,32",
};

TerrainDefs[205] = {
  damage: 10,
  id: 205,
  collisionMap:
    "0000000000000000000000000000000000000000000000000000f0000003f800000ff800003ffc0000fffe0001ffff0003ffff8003ffff8003ffffc003ffffc003ffffc003ffffc003ffff8003ffff0003ffff0003fffe0003fffc0001fffc00001ff8000003f000000000000000000000000000000000000000000000000000:32,32",
};

export const DefaultTerrainDef: TerrainDef = {
  damage: 10,
  id: 0,
  collisionMap:
    "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:32,32",
};

export let EntityDefs: { [id: number]: MapEntityDef } = {};
EntityDefs[EntityType.CANNON_BALL] = {
  damage: 10,
  health: 20,
  maxSpeed: 10,
  maxAcceleration: 0,
  collisionMap: "ffffff1:5,5",
};

EntityDefs[EntityType.UPGRADED_CANNON_BALL] = {
  damage: 20,
  health: 20,
  maxSpeed: 10,
  maxAcceleration: 0,
  collisionMap: "ffffff1:5,5",
};

EntityDefs[EntityType.SHIP_EXPLOSION] = {
  damage: 0,
  health: 10,
  maxSpeed: 0,
  maxAcceleration: 0,
  collisionMap:
    "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff:32,32",
};

EntityDefs[EntityType.TREASURE] = {
  damage: 0,
  health: 1000,
  maxSpeed: 0,
  maxAcceleration: 0,
  collisionMap: "7f8ff9ff3feffffffffff01e03c0:10,11",
};

EntityDefs[EntityType.WRECK] = {
  damage: 0,
  health: 20 * 60 * 5, // 5 minutes
  maxSpeed: 0,
  maxAcceleration: 0,
  collisionMap:
    "01ffc003fff803fffe01ffff80ffffe3fffff1fffff9fffffffffffffffffffffffffffffffffffffffffffffffffefffffe3ffffe1fffff0fffff87ffffc3ffffe1fffff0fffff87ffffc3ffffe1fffff0fffff87ffffc3ffffe1fffff0fffff87ffffc3ffffe1fffff0fffff87ffff83ffffc0ffffe07ffff03ffff81ffffc0ffffe03fffe00ffff007fff001fff800fffc007ffc001ffc000ffe0003fe0000fe00007e00001f000:54,25",
};

export const ShipDef: PlayerDef = {
  damage: 50,
  health: 100,
  maxSpeed: 2,
  maxAcceleration: 0.4,
  maxHealth: 100,
  reloadTime: 1000,
  waterResistenceFactor: 0.85,
  collisionMap:
    "01fe00000000001ffc0000000000ffffffff800007fffffffff0003ffffffffff001fffffffffff807fffffffffff03ffffffffffff0ffffffffffffe3ffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffe3ffffffffffff07fffffffffff01fffffffffff803ffffffffff0007ffffffffe0000ffffffff800001ffc00000000001fe0000000000:25,54",
};

export const PortDef: MapObjectDef = {
  damage: 0,
  collisionMap:
    "000000000000000000000000001ff800007ffe0001ffff8003ffffc007ffffe007ffffe00ffffff00ffffff01ffffff81ffffff81ffffff81ffffff81ffffff81ffffff81ffffff81ffffff81ffffff81ffffff80ffffff00ffffff007ffffe007ffffe003ffffc001ffff80007ffe00001ff800000000000000000000000000:32,32",
};
